### ISSUE TITLE
Fix Pedantic issues and add documentation to raise pub dev points

### ISSUE THREAD

**Issue by prikeshsavla** [PlugFox/throttling#3]
I have seen some copies of the source code being used as separate libraries. 
I can help out in making some doc and pedantic issue changes to better the pub points from the package site

**Comment by prikeshsavla** [comment]
I have fixed a lot of changes for pedantic in https://pub.dev/packages/username_generator. I would like to help out.

**Comment by PlugFox** [comment]
@prikeshsavla thx for PR.
I update package in pub with some upgrades)

Maybe in the future I will update the mechanisms just by reusing rxdart, leaving the API the same.
Don't worry about that and the size of the app, there is tree shaking included.

Perhaps I will add several stream transformers I use myself.

You can safely answer, if something is wrong, I will reopen the issue.

Have a good day)
