### ISSUE TITLE
demo link not found

### ISSUE THREAD

**Issue by koutja** [PlugFox/throttling#6]
Click on the link to view the code demo 
https://dartpad.dartlang.org/8630021e5c7ab9d27b74e86372f74c31

Opens page with 404 error:
Error: Page not found
The requested URL was not found on this server.

**Comment by PlugFox** [comment]
> Click on the link to view the code demo https://dartpad.dartlang.org/8630021e5c7ab9d27b74e86372f74c31
> 
> Opens page with 404 error: Error: Page not found The requested URL was not found on this server.

[Fixed](https://dartpad.dev?id=8630021e5c7ab9d27b74e86372f74c31)
